import {
  Alerts,
  Badges,
  Breadcrumbs,
  ButtonDropdowns,
  ButtonGroups,
  Buttons,
  Cards,
  Carousels,
  Charts,
  Collapses,
  Colors,
  Dashboard,
  Dropdowns,
  Flags,
  FontAwesome,
  Forms,
  Jumbotrons,
  ListGroups,
  Modals,
  Navbars,
  Navs,
  Paginations,
  Popovers,
  ProgressBar,
  SimpleLineIcons,
  BrandButtons,
  Switches,
  Tables,
  Tabs,
  Tooltips,
  Typography,
  Widgets,
  Stockq1,
  Stockq2,
  Stockq3,
  Roiq1,
  Roiq2,
  Roiq3,
  Roiq4,
  Industryq1,
  Industryq2,
  Industryq3,
  CompanyMain
} from './views';
import Full from './containers/Full';

// https://github.com/ReactTraining/react-router/tree/master/packages/react-router-config
const routes = [
  { path: '/', exact: true, name: 'Home', component: Full },
  { path: '/dashboard', name: 'Dashboard', component: Dashboard },
  { path: '/theme', exact: true, name: 'Theme', component: Colors },
  { path: '/stock', exact: true, name: 'Stock', component: Stockq1 },
  { path: '/stock/stockq1', name: 'Stockq1', component: Stockq1 },
  { path: '/stock/stockq2', name: 'Stockq2', component: Stockq2 },
  { path: '/stock/stockq3', name: 'Stockq3', component: Stockq3 },
  { path: '/roi', exact: true, name: 'Roi', component: Stockq1 },
  { path: '/roi/roiq1', name: 'Roiq1', component: Roiq1 },
  { path: '/roi/roiq2', name: 'Roiq2', component: Roiq2 },
  { path: '/roi/roiq3', name: 'Roiq3', component: Roiq3 },
  { path: '/roi/roiq4', name: 'Roiq4', component: Roiq4 },
  { path: '/industry', exact: true, name: 'Industry', component: Industryq1 },
  { path: '/industry/industryq1', name: 'Industryq1', component: Industryq1 },
  { path: '/industry/industryq2', name: 'Industryq2', component: Industryq2 },
  { path: '/industry/industryq3', name: 'Industryq3', component: Industryq3 },
  { path: '/company', exact: true, name: 'Company', component: CompanyMain },
  { path: '/company/companymain', name: 'CompanyMain', component: CompanyMain },
  { path: '/theme/colors', name: 'Colors', component: Colors },
  { path: '/theme/typography', name: 'Typography', component: Typography },
  { path: '/base', exact: true, name: 'Base', component: Cards },
  { path: '/base/cards', name: 'Cards', component: Cards },
  { path: '/base/forms', name: 'Forms', component: Forms },
  { path: '/base/switches', name: 'Swithces', component: Switches },
  { path: '/base/tables', name: 'Tables', component: Tables },
  { path: '/base/tabs', name: 'Tabs', component: Tabs },
  { path: '/base/breadcrumbs', name: 'Breadcrumbs', component: Breadcrumbs },
  { path: '/base/carousels', name: 'Carousels', component: Carousels },
  { path: '/base/collapses', name: 'Collapses', component: Collapses },
  { path: '/base/dropdowns', name: 'Dropdowns', component: Dropdowns },
  { path: '/base/jumbotrons', name: 'Jumbotrons', component: Jumbotrons },
  { path: '/base/list-groups', name: 'ListGroups', component: ListGroups },
  { path: '/base/navbars', name: 'Navbars', component: Navbars },
  { path: '/base/navs', name: 'Navs', component: Navs },
  { path: '/base/paginations', name: 'Paginations', component: Paginations },
  { path: '/base/popovers', name: 'Popovers', component: Popovers },
  { path: '/base/progress-bar', name: 'Progress Bar', component: ProgressBar },
  { path: '/base/tooltips', name: 'Tooltips', component: Tooltips },
  { path: '/buttons', exact: true, name: 'Buttons', component: Buttons },
  { path: '/buttons/buttons', name: 'Buttons', component: Buttons },
  { path: '/buttons/button-dropdowns', name: 'ButtonDropdowns', component: ButtonDropdowns },
  { path: '/buttons/button-groups', name: 'ButtonGroups', component: ButtonGroups },
  { path: '/buttons/brand-buttons', name: 'Brand Buttons', component: BrandButtons },
  { path: '/icons', exact: true, name: 'Icons', component: Flags },
  { path: '/icons/flags', name: 'Flags', component: Flags },
  { path: '/icons/font-awesome', name: 'Font Awesome', component: FontAwesome },
  { path: '/icons/simple-line-icons', name: 'Simple Line Icons', component: SimpleLineIcons },
  { path: '/notifications', exact: true, name: 'Notifications', component: Alerts },
  { path: '/notifications/alerts', name: 'Alerts', component: Alerts },
  { path: '/notifications/badges', name: 'Badges', component: Badges },
  { path: '/notifications/modals', name: 'Modals', component: Modals },
  { path: '/widgets', name: 'Widgets', component: Widgets },
  { path: '/charts', name: 'Charts', component: Charts },
];

export default routes;
